org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=simple_ender_backpack
mod.name=Simple Ender Backpack
mod.group=me.pajic
mod.version=1.1.0
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Portable ender storage with Accessories support
mod.sources_url=https://github.com/pajicadvance/simple-ender-backpack
mod.homepage_url=https://modrinth.com/mod/simple-ender-backpack
mod.issues_url=https://github.com/pajicadvance/simple-ender-backpack/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.parchment=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.accessories=[VERSIONED]

publish.modrinth=6LdAHg5g
publish.curseforge=1165235
publish.github=false
